### ISSUE TITLE
Sprint Notes

### ISSUE THREAD

**Issue by steveoh** [agrc/AddressPointEditor#21]
Create these issues:
- [x] User Management (#22)
  - email, phone number, name, agency
- [x] Edits should store user name and time stamp (#23)
- [x] Expand edit boxes to all of the fields need to be editable and visible with the exception of `AddSystem`, `UTAddPtID`, `FullAdd` (#24)
- [x] Download (#25)
- [x] Remove leaderboard (#26)
- [x] Find Place (#27)
- [x] Point at new data (#28)
- [x] Suggest change - low priority (#29)
- [x] Parcel identify - low priority (#20)
